### ISSUE TITLE
[FE] 각종 버그

### ISSUE THREAD

**Issue by d0422** [boostcampwm2023/web05-AlgoITNi#111]
# Todo
- [x] 선택된 장비가 정확하게 보이지 않는 이슈
- [x] 코드 에디터 높이가 깨지는 이슈
- [x] 환경설정 UI가 이상함
- [x] 불러오기 버튼 글자가 적용안된 것 같음
- [x] 링크 입력하기 디자인이 이상함 
- [ ] 코드에디터 저장하기에 코드 입력값이 없으면 저장되지 않는 기능 추가
- [x] 클라우드 불러오기 패딩 수정
- [x] 모달 입력받는 부분 form으로 변경
