### ISSUE TITLE
[FE] 랜덤 닉네임을 채팅에 적용시키기

### ISSUE THREAD

**Issue by d0422** [boostcampwm2023/web05-AlgoITNi#136]
# Todo
- [x] 랜덤 닉네임 생성
- [x] 랜덤 닉네임을 소켓서버로 전송
- [x] 로그인 리다이렉션시 랜덤 닉네임 유지
