### ISSUE TITLE
[FE] AI 질문하기 기능 추가

### ISSUE THREAD

**Issue by HBSPS** [boostcampwm2023/web05-AlgoITNi#177]
# TODO
- [x] 채팅 input에 AI 질문 토글 버튼 추가
- [x] 소켓 통신 추가
- [x] 렌더링
- [x] 채팅 에러 핸들링
