### ISSUE TITLE
[FE] 코드 에디터 컴포넌트 UI 구현

### ISSUE THREAD

**Issue by HBSPS** [boostcampwm2023/web05-AlgoITNi#26]
# TODO
- [x] 기본 UI 구성
- [x] ~~엔터 입력 시 좌측의 라인 넘버 증가~~
- [x] 엔터 미입력 상태에서 최대 길이 넘기는 경우 라인 넘버 증가 없이 줄바꿈
