### ISSUE TITLE
[FE] socket연결 방식 변경, room관련 오류 해결

### ISSUE THREAD

**Issue by d0422** [boostcampwm2023/web05-AlgoITNi#74]
# Todo
- [x] 소켓 연결 방식 변경 (fetch한 url로 연결)
- [x] room에 처음 입장하는 경우, media device list를 가져오지 못하는 문제 해결
- [x] 비디오, 오디오 on/off와 관계없이 stream을 변경하면 on/off가 무시되던 오류 해결
