### ISSUE TITLE
[FE] 채팅 기능 구현

### ISSUE THREAD

**Issue by HBSPS** [boostcampwm2023/web05-AlgoITNi#89]
# TODO
- [x] 채팅 서버 연결
- [ ] 채팅 기능 구현
- [x] 채팅 UI 구성
